FROM ubuntu

WORKDIR /client

RUN apt-get update && apt-get install -y python3 python3-pip

COPY . /client/

RUN python3 -m pip install -r src/DetectEmotion/requirements.txt

EXPOSE 2106

CMD [ "python3", "client_conn.py" ]
